// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAtNL0Fvewh0YBA2u_-94ZPxVWMOi3rI',
    appId: '1:625666225680:web:8a035586bc51c787f5bc95',
    messagingSenderId: '625666225680',
    projectId: 'safetrek-f7149',
    authDomain: 'safetrek-f7149.firebaseapp.com',
    storageBucket: 'safetrek-f7149.firebasestorage.app',
    measurementId: 'G-KLGJ3CNDN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Hi9MQe4HeqsTj2GkSj-kO9YXWQrsBIk',
    appId: '1:625666225680:android:c0a79b841d0ca45af5bc95',
    messagingSenderId: '625666225680',
    projectId: 'safetrek-f7149',
    storageBucket: 'safetrek-f7149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD4lPJLXI-MWAK4Wz9wI1EqKnv7CDaV5s',
    appId: '1:625666225680:ios:0a6ce7564ac44a46f5bc95',
    messagingSenderId: '625666225680',
    projectId: 'safetrek-f7149',
    storageBucket: 'safetrek-f7149.firebasestorage.app',
    iosBundleId: 'com.example.vesiaoSafetrek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD4lPJLXI-MWAK4Wz9wI1EqKnv7CDaV5s',
    appId: '1:625666225680:ios:0a6ce7564ac44a46f5bc95',
    messagingSenderId: '625666225680',
    projectId: 'safetrek-f7149',
    storageBucket: 'safetrek-f7149.firebasestorage.app',
    iosBundleId: 'com.example.vesiaoSafetrek',
  );

}